### ISSUE TITLE
Modification in filter.py for 100X

### ISSUE THREAD

**Issue by abcklaus** [fquinto/bticinoClasse300x#14]
Bticino CLASSE 100 X doesn't support python3. Therefore filter.py is not working without modification.

Problem is this line in code:

`print(line[line.find('*'):], end="")`
 
With this enhancement filter should work on Python 2 & 3:

`from __future__ import print_function`

**Comment by emics** [comment]
for 100X I have also changed in file StartMqttSend in line 4 and 6
`/usr/bin/python3`
with  this
`/usr/bin/python2`

**Comment by msanchezt** [comment]
TcpDump2Mqtt file has as well a mention to python3 that needs to be renamed to python2

**Comment by fquinto** [comment]
Thanks to @PabloCamp0s
