### ISSUE TITLE
BTCINO C100X

### ISSUE THREAD

**Issue by gbarrena** [fquinto/bticinoClasse300x#21]
I have flashed the C100x with version 1.5.5 modified for mosquito, I have put the mosquito server the ports and the credentials but the intercon does not issue anything to the mosquito broker.

Any ideas?

can anyone help me?

**Comment by msanchezt** [comment]
C100X does not have Python3, only Python2.7, you need to modify 2 files under:  /etc/tcpdump2mqtt/, whenever python3 is mentioned replace it by python2

As well, modify file:  /home/root/filter.py

Line #8 with the print should be like this:
     print(line[line.find('*'):]+"\n")

**Comment by AlbertoAIG** [comment]
> C100X does not have Python3, only Python2.7, you need to modify 2 files under: /etc/tcpdump2mqtt/, whenever python3 is mentioned replace it by python2
> 
> As well, modify file: /home/root/filter.py
> 
> Line #8 with the print should be like this: print(line[line.find('*'):]+"\n")

Hi,

I can't edit this file, it says read only file.

**Comment by fquinto** [comment]
New version of python creator script. This is done there. Thank to @PabloCamp0s
